stages:
  - test

lint:
  stage: test
  image: python:3.8
  before_script:
    - pip install black
  script:
    - black --check .
  allow_failure: false 

testcov:
  stage: test
  image: continuumio/miniconda3
  before_script:
    - conda env create -q -f ./env/face_detection_age_from-history.yaml -n myenv --force
    - conda init bash
    - source ~/.bashrc
    - conda activate myenv
    - pip install pytest pytest-cov
  script:
    - pytest --cov api/
    - curl -Os https://cli.codecov.io/latest/linux/codecov
    - chmod +x codecov
    - ./codecov upload-process -t $CODECOV_TOKEN
